<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-6830-1658839462/blob/main/Sangeetha_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Split this string s = "Hi there Sam!"

In [1]:
s="Hi there Sam!"
print(s.split(" "))

['Hi', 'there', 'Sam!']


2.Use .format() to print the following string. Output should be: The diameter of Earth is 12742 kilometers. planet = "Earth" diameter = 12742

In [2]:
print("The diameter of {planet} is {diameter} kilometers.".format(planet='Earth',diameter=12742))

The diameter of Earth is 12742 kilometers.


3.In this nest dictionary grab the word "hello" d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d1=d['k1'][3]

In [5]:
d2=d1['tricky'][3]

In [6]:
d2

{'target': [1, 2, 3, 'hello']}

In [7]:
d2['target'][3]

'hello'

4.Create an array of 10 zeros? 4.2 Create an array of 10 fives?

In [8]:
import numpy as np
k1=np.arange(10)
k2=np.arange(10)
k1.fill(0)
k2.fill(5)

In [9]:
print(k1)
print(k2)

[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


5.Create an array of all the even integers from 20 to 35

6.Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7.Concatinate a and b a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.arange(20,35,2)
print(a)

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a,b),axis=0))

[1 2 3 4 5 6]


8.Create a dataframe with 3 rows and 2 columns

In [12]:
import pandas as pd
row=['a','b','c']
col=[1,2]
l=np.arange(1,7)
l=l.reshape(3,2)
r=pd.DataFrame(l,index=row,columns=col)

In [13]:
r

1  2
a  1  2
b  3  4
c  5  6

9.Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

10.Create 2D list to DataFrame lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
pd.date_range(start="2023-01-01",end="2023-02-10")

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)

In [16]:
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24